version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  gosec:
    excludes:
      - G115 # integer overflow conversion int -> int32
      - G117 # Exported struct field matches secret pattern
