name: PR Validation

on:
  pull_request:
    branches: ["master", "main"]

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    permissions:
      contents: read
      packages: read
    with:
      image_tag: pr-test
